pipeline{
  agent { label 'built-in' }
  tools{
    maven '3.8.6'
  }
  stages{
    stage("Package Resources"){
      steps{
        sh """
          mvn clean package
        """
      }
    }

    stage("Build Image"){
      steps{
        sh """
          docker build -t xeng/spring-app:11.22.33 .
        """
      }
    }

    stage("Push to Registry"){
      steps{
        withCredentials([usernamePassword(credentialsId: 'xeng-docker-hub', passwordVariable: 'PASSWORD', usernameVariable: 'USERNAME')]) {
          sh """
            docker login -u $USERNAME -p $PASSWORD
            docker push xeng/spring-app:11.22.33
          """
        }
      }
    }

    stage("Deploy App"){
      steps{
        sh """
          ansible-playbook -i kubernetes/ansible/inventory.ini workers \
            -e workspace={{ $WORKSPACE }} \
            kubernetes/ansible/playbooks/deploy.yml
        """
      }
    }
    
  }
}
