pipeline{
  agent { label 'built-in' }
  tools{
    maven '3.8.6'
  }
  stages{
    stage("Package Resources"){
      steps{
        sh """
          mvn clean package
        """
      }
    }

    stage("Build Image"){
      steps{
        sh """
          docker build -t xeng/spring-app:$BUILD_NUMBER .
        """
      }
    }

    stage("Push to Registry"){
      steps{
        withCredentials([usernamePassword(credentialsId: 'xeng-docker-hub', passwordVariable: 'PASSWORD', usernameVariable: 'USERNAME')]) {
          sh """
            docker login -u $USERNAME -p $PASSWORD
            docker push xeng/spring-app:$BUILD_NUMBER
          """
        }
      }
    }

    stage("Update Version"){
      steps{
        sh """
          sed -i "s+image:.*+image: xeng/spring-app:$BUILD_NUMBER+" kubernetes/spring-app.yml
        """
      }
    }

    stage("Deploy App"){
      steps{
        sh """
          ansible-playbook -i kubernetes/ansible/inventory.ini -l workers \
            -e workspace=$WORKSPACE \
            kubernetes/ansible/playbooks/deploy.yml
        """
      }
    }
    
  }
}
