- hosts: all
  become: true
  vars:
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
  tasks:
    - name: Copy Deploy file
      copy:
        src: "{{ workspace }}/kubernetes"
        dest: /opt
        owner: leangsengk90
        group: leangsengk90
        mode: '0777'
    - name: Deploy App
      shell: |
        kubectl apply -f /opt/kubernetes/spring-app.yml
