- hosts: all
  become: true
  vars: 
    ansible_ssh_common_args: "-o StrictHostKeyChecking=yes"
  tasks:
    - name: Deploy App
      shell: |
        helm repo update
        helm upgrade my-app-uat helm-repo/my-app-uat --install
        
