- hosts: all
  become: true
  vars: 
    ansible_ssh_common_args: "-o StrictHostKeyChecking=yes"
  tasks:
    - name: Copy file to Kubernetes Server
      copy:
        src: "{{ workspace }}/kubernetes"
        dest: /opt
        owner: leangsengk90
        group: leangsengk90
        mode: '0700'

    - name: Deploy App
      shell: |
        kubectl apply -f /opt/kubernetes/spring-app.yml
        
